spring:
  application:
    name: app-search
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  cache:
    caffeine:
      spec: maximumSize=10, expireAfterWrite=10s, recordStats

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        max-connections: 200
        max-connections-per-route: 400
        hc5:
          enabled: true
          pool-reuse-policy: fifo
          pool-concurrency-policy: strict

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

resilience4j:
  thread-pool-bulkhead:
    configs:
      default:
        base-config: default
        max-thread-pool-size: 200

client:
  kakao:
    authorization: KakaoAK b6a00360f01be0070bdac0feecf14ebb
  naver:
    clientId: E1qAJ8z2ojKD643WFfEX
    clientSecret: jsDrQuGbA6

logging:
  level:
    org.hibernate.sql: debug
    feign: error
