spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


client:
  kakao:
    authorization: KakaoAK b6a00360f01be0070bdac0feecf14ebb
  naver:
    clientId: E1qAJ8z2ojKD643WFfEX
    clientSecret: jsDrQuGbA6

logging:
  level:
    org.hibernate.sql: debug